spring:
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      name: commonyml,SECURITY-SERVICE
      uri: http://localhost:8888/
  application:
    name: SECURITY-SERVICE
server:
  port: '8095'
