spring:
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      name: commonyml,LEAVES-SERVICE
      uri: http://localhost:8888/
  application:
    name: LEAVES-SERVICE
server:
  port: '8092'
