spring:
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      name: commonyml,EMPLOYEE-SERVICE
      uri: http://localhost:8888/
  application:
    name: EMPLOYEE-SERVICE
server:
  port: '8090'
